//LOCAL VARIABLE
var X = 11; //ASSIGNING VARIABLE
function Add_numbers_1() { //ASSIGNING VARIABLE LABLE
    document.write(20 + X + "<br>"); //TELLING SCREEN TO DISPLAY EQUATION IN PARENTHASIS USING GLOBAL VARIABLE "X", WITH BREAK ADDED
}
function Add_numbers_2() { //ASSIGNING VARIABLE LABEL
    document.write(X + 100 + "<br>"); //TELLING SCREEN TO DISPLAY EQUATION IN PARENTHASIS USING GLOBAL VARIABLE "X", WITH BREAK ADDED
}
Add_numbers_1(); //ALLOWING FUNCTION TO BE CALLED
Add_numbers_2(); //ALLOWING FUNCTION TO BE CALLED
function Add_numbers_3() { //LABELING FUNCTION
    X = 11; //ASSIGNING VARIABLE
    document.write(20 + X + "<br>");//ADDING EQUATION IN PARENTHASIS USING LOCAL VARIABLE X
}
function Add_numbers_4() {//ASSIGNING FUNCTION LABEL
    X = 12; //ASSIGNING VARIABLE
    document.write(X + 100 + "<br>"); //ADDING EQUATION & DISPLAYING
}
Add_numbers_3();//ALLOWING FUNCTION TO BE CALLED
Add_numbers_4();//ALLOWING FUNCTION TO BE CALLED
function Add_numbers_5() { //ADDING LABEL
    X = 11; //ASSIGINING VARIABLE
    document.write(20 + X + "<br>");//DISPLAYING ADDED EQUATION
}
function Add_numbers_6() {//LABELING FUNCTION
    console.log(X + 100 + "<br>"); //FUNCTION WITH ERROR - X WILL NOT BE IDENTIFIED SINCE THE PREVIOUS X IS A LOCAL VARIABLE TO THE PREVIOUS FUNCTION - CONSOLE WILL HELP WITH DEBUGGIN IN THE CONSOLE
}
Add_numbers_5();//ALLOWING FUNCTION TO BE CALLED
Add_numbers_6();//ALLOWING FUNCTION TO BE CALLED
//END LOCAL VARIABLE




//IF STATEMENT
function get_Date() { //ADDING LABEL
    if (new Date() .getHours() > 14) { //IF THE CURRENT DAYS TIME IS GREATER THAN 2PM, THEN PRINT WHAT IS IN THE GET.DOCUMENT FUNCTION
        document.getElementById("Greeting").innerHTML = "It is later than 2pm"; //GET DOCUMENT FUNTION WICH WILL DISPLAY ON HTML WHERE THE "GREETING" ID IS
    }
}
//END IF STATEMENT


//TIME FUNCTION
function Time_function() { //ADDING LABEL TO FUNCTION
    var Time = new Date().getHours(); //ASSIGNING VARIABLE TO COMMAND
    var Reply; //LABELING VARIABLE THAT INCLUDES THE BELOW FUNCTIONS
    if (Time < 12 == Time > 0) { //IF THE TIME IS BEFORE NOON AND PAST MIDNIGHT
        Reply = "It is morning time!"; //(CONT. - THEN IT WILL BE MORNING TIME
    }
    else if (Time >= 12 == Time < 18) { //BUT IF THE TIME IS PAST OR IS NOON, BUT BEFORE 6
        Reply = "It is afternoon."; //CONT. - THEN IT IS THE AFTERNOON
    }
    else { //HOWEVER, IF IT IS NOT ANY OF THE PREVIOUS TIMES
        Reply = "It is evening time."; //THEN IT MUST BE EVENING TIME, THE ONLY TIME FRAME REMAINING
    }
    document.getElementById("Time_of_day").innerHTML = Reply; //DISPLAY THE CORRESPONDING "REPLY" IN THE HTML WITH THE "TIME_OF_DAY" ID
}
//END TIME FUNCTION